
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model EventUser
 * 
 */
export type EventUserModel = runtime.Types.Result.DefaultSelection<Prisma.$EventUserPayload>

export type AggregateEventUser = {
  _count: EventUserCountAggregateOutputType | null
  _avg: EventUserAvgAggregateOutputType | null
  _sum: EventUserSumAggregateOutputType | null
  _min: EventUserMinAggregateOutputType | null
  _max: EventUserMaxAggregateOutputType | null
}

export type EventUserAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  eventId: number | null
}

export type EventUserSumAggregateOutputType = {
  id: number | null
  userId: number | null
  eventId: number | null
}

export type EventUserMinAggregateOutputType = {
  id: number | null
  userId: number | null
  eventId: number | null
}

export type EventUserMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  eventId: number | null
}

export type EventUserCountAggregateOutputType = {
  id: number
  userId: number
  eventId: number
  _all: number
}


export type EventUserAvgAggregateInputType = {
  id?: true
  userId?: true
  eventId?: true
}

export type EventUserSumAggregateInputType = {
  id?: true
  userId?: true
  eventId?: true
}

export type EventUserMinAggregateInputType = {
  id?: true
  userId?: true
  eventId?: true
}

export type EventUserMaxAggregateInputType = {
  id?: true
  userId?: true
  eventId?: true
}

export type EventUserCountAggregateInputType = {
  id?: true
  userId?: true
  eventId?: true
  _all?: true
}

export type EventUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventUser to aggregate.
   */
  where?: Prisma.EventUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventUsers to fetch.
   */
  orderBy?: Prisma.EventUserOrderByWithRelationInput | Prisma.EventUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventUsers
  **/
  _count?: true | EventUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EventUserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EventUserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventUserMaxAggregateInputType
}

export type GetEventUserAggregateType<T extends EventUserAggregateArgs> = {
      [P in keyof T & keyof AggregateEventUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventUser[P]>
    : Prisma.GetScalarType<T[P], AggregateEventUser[P]>
}




export type EventUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventUserWhereInput
  orderBy?: Prisma.EventUserOrderByWithAggregationInput | Prisma.EventUserOrderByWithAggregationInput[]
  by: Prisma.EventUserScalarFieldEnum[] | Prisma.EventUserScalarFieldEnum
  having?: Prisma.EventUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventUserCountAggregateInputType | true
  _avg?: EventUserAvgAggregateInputType
  _sum?: EventUserSumAggregateInputType
  _min?: EventUserMinAggregateInputType
  _max?: EventUserMaxAggregateInputType
}

export type EventUserGroupByOutputType = {
  id: number
  userId: number
  eventId: number
  _count: EventUserCountAggregateOutputType | null
  _avg: EventUserAvgAggregateOutputType | null
  _sum: EventUserSumAggregateOutputType | null
  _min: EventUserMinAggregateOutputType | null
  _max: EventUserMaxAggregateOutputType | null
}

type GetEventUserGroupByPayload<T extends EventUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventUserGroupByOutputType[P]>
      }
    >
  >



export type EventUserWhereInput = {
  AND?: Prisma.EventUserWhereInput | Prisma.EventUserWhereInput[]
  OR?: Prisma.EventUserWhereInput[]
  NOT?: Prisma.EventUserWhereInput | Prisma.EventUserWhereInput[]
  id?: Prisma.IntFilter<"EventUser"> | number
  userId?: Prisma.IntFilter<"EventUser"> | number
  eventId?: Prisma.IntFilter<"EventUser"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}

export type EventUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  event?: Prisma.EventOrderByWithRelationInput
}

export type EventUserWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId_eventId?: Prisma.EventUserUserIdEventIdCompoundUniqueInput
  AND?: Prisma.EventUserWhereInput | Prisma.EventUserWhereInput[]
  OR?: Prisma.EventUserWhereInput[]
  NOT?: Prisma.EventUserWhereInput | Prisma.EventUserWhereInput[]
  userId?: Prisma.IntFilter<"EventUser"> | number
  eventId?: Prisma.IntFilter<"EventUser"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
}, "id" | "userId_eventId">

export type EventUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  _count?: Prisma.EventUserCountOrderByAggregateInput
  _avg?: Prisma.EventUserAvgOrderByAggregateInput
  _max?: Prisma.EventUserMaxOrderByAggregateInput
  _min?: Prisma.EventUserMinOrderByAggregateInput
  _sum?: Prisma.EventUserSumOrderByAggregateInput
}

export type EventUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventUserScalarWhereWithAggregatesInput | Prisma.EventUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventUserScalarWhereWithAggregatesInput | Prisma.EventUserScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"EventUser"> | number
  userId?: Prisma.IntWithAggregatesFilter<"EventUser"> | number
  eventId?: Prisma.IntWithAggregatesFilter<"EventUser"> | number
}

export type EventUserCreateInput = {
  user: Prisma.UserCreateNestedOneWithoutEventsInput
  event: Prisma.EventCreateNestedOneWithoutUsersInput
}

export type EventUserUncheckedCreateInput = {
  id?: number
  userId: number
  eventId: number
}

export type EventUserUpdateInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutEventsNestedInput
  event?: Prisma.EventUpdateOneRequiredWithoutUsersNestedInput
}

export type EventUserUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EventUserCreateManyInput = {
  id?: number
  userId: number
  eventId: number
}

export type EventUserUpdateManyMutationInput = {

}

export type EventUserUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EventUserListRelationFilter = {
  every?: Prisma.EventUserWhereInput
  some?: Prisma.EventUserWhereInput
  none?: Prisma.EventUserWhereInput
}

export type EventUserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventUserUserIdEventIdCompoundUniqueInput = {
  userId: number
  eventId: number
}

export type EventUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventUserAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventUserSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type EventUserCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutEventInput, Prisma.EventUserUncheckedCreateWithoutEventInput> | Prisma.EventUserCreateWithoutEventInput[] | Prisma.EventUserUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutEventInput | Prisma.EventUserCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventUserCreateManyEventInputEnvelope
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
}

export type EventUserUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutEventInput, Prisma.EventUserUncheckedCreateWithoutEventInput> | Prisma.EventUserCreateWithoutEventInput[] | Prisma.EventUserUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutEventInput | Prisma.EventUserCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventUserCreateManyEventInputEnvelope
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
}

export type EventUserUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutEventInput, Prisma.EventUserUncheckedCreateWithoutEventInput> | Prisma.EventUserCreateWithoutEventInput[] | Prisma.EventUserUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutEventInput | Prisma.EventUserCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventUserUpsertWithWhereUniqueWithoutEventInput | Prisma.EventUserUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventUserCreateManyEventInputEnvelope
  set?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  disconnect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  delete?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  update?: Prisma.EventUserUpdateWithWhereUniqueWithoutEventInput | Prisma.EventUserUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventUserUpdateManyWithWhereWithoutEventInput | Prisma.EventUserUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventUserScalarWhereInput | Prisma.EventUserScalarWhereInput[]
}

export type EventUserUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutEventInput, Prisma.EventUserUncheckedCreateWithoutEventInput> | Prisma.EventUserCreateWithoutEventInput[] | Prisma.EventUserUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutEventInput | Prisma.EventUserCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventUserUpsertWithWhereUniqueWithoutEventInput | Prisma.EventUserUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventUserCreateManyEventInputEnvelope
  set?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  disconnect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  delete?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  update?: Prisma.EventUserUpdateWithWhereUniqueWithoutEventInput | Prisma.EventUserUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventUserUpdateManyWithWhereWithoutEventInput | Prisma.EventUserUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventUserScalarWhereInput | Prisma.EventUserScalarWhereInput[]
}

export type EventUserCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutUserInput, Prisma.EventUserUncheckedCreateWithoutUserInput> | Prisma.EventUserCreateWithoutUserInput[] | Prisma.EventUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutUserInput | Prisma.EventUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EventUserCreateManyUserInputEnvelope
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
}

export type EventUserUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutUserInput, Prisma.EventUserUncheckedCreateWithoutUserInput> | Prisma.EventUserCreateWithoutUserInput[] | Prisma.EventUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutUserInput | Prisma.EventUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EventUserCreateManyUserInputEnvelope
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
}

export type EventUserUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutUserInput, Prisma.EventUserUncheckedCreateWithoutUserInput> | Prisma.EventUserCreateWithoutUserInput[] | Prisma.EventUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutUserInput | Prisma.EventUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EventUserUpsertWithWhereUniqueWithoutUserInput | Prisma.EventUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EventUserCreateManyUserInputEnvelope
  set?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  disconnect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  delete?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  update?: Prisma.EventUserUpdateWithWhereUniqueWithoutUserInput | Prisma.EventUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EventUserUpdateManyWithWhereWithoutUserInput | Prisma.EventUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EventUserScalarWhereInput | Prisma.EventUserScalarWhereInput[]
}

export type EventUserUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EventUserCreateWithoutUserInput, Prisma.EventUserUncheckedCreateWithoutUserInput> | Prisma.EventUserCreateWithoutUserInput[] | Prisma.EventUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EventUserCreateOrConnectWithoutUserInput | Prisma.EventUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EventUserUpsertWithWhereUniqueWithoutUserInput | Prisma.EventUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EventUserCreateManyUserInputEnvelope
  set?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  disconnect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  delete?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  connect?: Prisma.EventUserWhereUniqueInput | Prisma.EventUserWhereUniqueInput[]
  update?: Prisma.EventUserUpdateWithWhereUniqueWithoutUserInput | Prisma.EventUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EventUserUpdateManyWithWhereWithoutUserInput | Prisma.EventUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EventUserScalarWhereInput | Prisma.EventUserScalarWhereInput[]
}

export type EventUserCreateWithoutEventInput = {
  user: Prisma.UserCreateNestedOneWithoutEventsInput
}

export type EventUserUncheckedCreateWithoutEventInput = {
  id?: number
  userId: number
}

export type EventUserCreateOrConnectWithoutEventInput = {
  where: Prisma.EventUserWhereUniqueInput
  create: Prisma.XOR<Prisma.EventUserCreateWithoutEventInput, Prisma.EventUserUncheckedCreateWithoutEventInput>
}

export type EventUserCreateManyEventInputEnvelope = {
  data: Prisma.EventUserCreateManyEventInput | Prisma.EventUserCreateManyEventInput[]
  skipDuplicates?: boolean
}

export type EventUserUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventUserWhereUniqueInput
  update: Prisma.XOR<Prisma.EventUserUpdateWithoutEventInput, Prisma.EventUserUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventUserCreateWithoutEventInput, Prisma.EventUserUncheckedCreateWithoutEventInput>
}

export type EventUserUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventUserWhereUniqueInput
  data: Prisma.XOR<Prisma.EventUserUpdateWithoutEventInput, Prisma.EventUserUncheckedUpdateWithoutEventInput>
}

export type EventUserUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventUserScalarWhereInput
  data: Prisma.XOR<Prisma.EventUserUpdateManyMutationInput, Prisma.EventUserUncheckedUpdateManyWithoutEventInput>
}

export type EventUserScalarWhereInput = {
  AND?: Prisma.EventUserScalarWhereInput | Prisma.EventUserScalarWhereInput[]
  OR?: Prisma.EventUserScalarWhereInput[]
  NOT?: Prisma.EventUserScalarWhereInput | Prisma.EventUserScalarWhereInput[]
  id?: Prisma.IntFilter<"EventUser"> | number
  userId?: Prisma.IntFilter<"EventUser"> | number
  eventId?: Prisma.IntFilter<"EventUser"> | number
}

export type EventUserCreateWithoutUserInput = {
  event: Prisma.EventCreateNestedOneWithoutUsersInput
}

export type EventUserUncheckedCreateWithoutUserInput = {
  id?: number
  eventId: number
}

export type EventUserCreateOrConnectWithoutUserInput = {
  where: Prisma.EventUserWhereUniqueInput
  create: Prisma.XOR<Prisma.EventUserCreateWithoutUserInput, Prisma.EventUserUncheckedCreateWithoutUserInput>
}

export type EventUserCreateManyUserInputEnvelope = {
  data: Prisma.EventUserCreateManyUserInput | Prisma.EventUserCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type EventUserUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.EventUserWhereUniqueInput
  update: Prisma.XOR<Prisma.EventUserUpdateWithoutUserInput, Prisma.EventUserUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.EventUserCreateWithoutUserInput, Prisma.EventUserUncheckedCreateWithoutUserInput>
}

export type EventUserUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.EventUserWhereUniqueInput
  data: Prisma.XOR<Prisma.EventUserUpdateWithoutUserInput, Prisma.EventUserUncheckedUpdateWithoutUserInput>
}

export type EventUserUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.EventUserScalarWhereInput
  data: Prisma.XOR<Prisma.EventUserUpdateManyMutationInput, Prisma.EventUserUncheckedUpdateManyWithoutUserInput>
}

export type EventUserCreateManyEventInput = {
  id?: number
  userId: number
}

export type EventUserUpdateWithoutEventInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutEventsNestedInput
}

export type EventUserUncheckedUpdateWithoutEventInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EventUserUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EventUserCreateManyUserInput = {
  id?: number
  eventId: number
}

export type EventUserUpdateWithoutUserInput = {
  event?: Prisma.EventUpdateOneRequiredWithoutUsersNestedInput
}

export type EventUserUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EventUserUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type EventUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  eventId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventUser"]>

export type EventUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  eventId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventUser"]>

export type EventUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  eventId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventUser"]>

export type EventUserSelectScalar = {
  id?: boolean
  userId?: boolean
  eventId?: boolean
}

export type EventUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "eventId", ExtArgs["result"]["eventUser"]>
export type EventUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}
export type EventUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
}

export type $EventUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventUser"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    event: Prisma.$EventPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    eventId: number
  }, ExtArgs["result"]["eventUser"]>
  composites: {}
}

export type EventUserGetPayload<S extends boolean | null | undefined | EventUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventUserPayload, S>

export type EventUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventUserCountAggregateInputType | true
  }

export interface EventUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventUser'], meta: { name: 'EventUser' } }
  /**
   * Find zero or one EventUser that matches the filter.
   * @param {EventUserFindUniqueArgs} args - Arguments to find a EventUser
   * @example
   * // Get one EventUser
   * const eventUser = await prisma.eventUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventUserFindUniqueArgs>(args: Prisma.SelectSubset<T, EventUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventUserFindUniqueOrThrowArgs} args - Arguments to find a EventUser
   * @example
   * // Get one EventUser
   * const eventUser = await prisma.eventUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserFindFirstArgs} args - Arguments to find a EventUser
   * @example
   * // Get one EventUser
   * const eventUser = await prisma.eventUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventUserFindFirstArgs>(args?: Prisma.SelectSubset<T, EventUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserFindFirstOrThrowArgs} args - Arguments to find a EventUser
   * @example
   * // Get one EventUser
   * const eventUser = await prisma.eventUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventUsers
   * const eventUsers = await prisma.eventUser.findMany()
   * 
   * // Get first 10 EventUsers
   * const eventUsers = await prisma.eventUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventUserWithIdOnly = await prisma.eventUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventUserFindManyArgs>(args?: Prisma.SelectSubset<T, EventUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventUser.
   * @param {EventUserCreateArgs} args - Arguments to create a EventUser.
   * @example
   * // Create one EventUser
   * const EventUser = await prisma.eventUser.create({
   *   data: {
   *     // ... data to create a EventUser
   *   }
   * })
   * 
   */
  create<T extends EventUserCreateArgs>(args: Prisma.SelectSubset<T, EventUserCreateArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventUsers.
   * @param {EventUserCreateManyArgs} args - Arguments to create many EventUsers.
   * @example
   * // Create many EventUsers
   * const eventUser = await prisma.eventUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventUserCreateManyArgs>(args?: Prisma.SelectSubset<T, EventUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventUsers and returns the data saved in the database.
   * @param {EventUserCreateManyAndReturnArgs} args - Arguments to create many EventUsers.
   * @example
   * // Create many EventUsers
   * const eventUser = await prisma.eventUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventUsers and only return the `id`
   * const eventUserWithIdOnly = await prisma.eventUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventUser.
   * @param {EventUserDeleteArgs} args - Arguments to delete one EventUser.
   * @example
   * // Delete one EventUser
   * const EventUser = await prisma.eventUser.delete({
   *   where: {
   *     // ... filter to delete one EventUser
   *   }
   * })
   * 
   */
  delete<T extends EventUserDeleteArgs>(args: Prisma.SelectSubset<T, EventUserDeleteArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventUser.
   * @param {EventUserUpdateArgs} args - Arguments to update one EventUser.
   * @example
   * // Update one EventUser
   * const eventUser = await prisma.eventUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventUserUpdateArgs>(args: Prisma.SelectSubset<T, EventUserUpdateArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventUsers.
   * @param {EventUserDeleteManyArgs} args - Arguments to filter EventUsers to delete.
   * @example
   * // Delete a few EventUsers
   * const { count } = await prisma.eventUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventUsers
   * const eventUser = await prisma.eventUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventUserUpdateManyArgs>(args: Prisma.SelectSubset<T, EventUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventUsers and returns the data updated in the database.
   * @param {EventUserUpdateManyAndReturnArgs} args - Arguments to update many EventUsers.
   * @example
   * // Update many EventUsers
   * const eventUser = await prisma.eventUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventUsers and only return the `id`
   * const eventUserWithIdOnly = await prisma.eventUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventUser.
   * @param {EventUserUpsertArgs} args - Arguments to update or create a EventUser.
   * @example
   * // Update or create a EventUser
   * const eventUser = await prisma.eventUser.upsert({
   *   create: {
   *     // ... data to create a EventUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventUser we want to update
   *   }
   * })
   */
  upsert<T extends EventUserUpsertArgs>(args: Prisma.SelectSubset<T, EventUserUpsertArgs<ExtArgs>>): Prisma.Prisma__EventUserClient<runtime.Types.Result.GetResult<Prisma.$EventUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserCountArgs} args - Arguments to filter EventUsers to count.
   * @example
   * // Count the number of EventUsers
   * const count = await prisma.eventUser.count({
   *   where: {
   *     // ... the filter for the EventUsers we want to count
   *   }
   * })
  **/
  count<T extends EventUserCountArgs>(
    args?: Prisma.Subset<T, EventUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventUserAggregateArgs>(args: Prisma.Subset<T, EventUserAggregateArgs>): Prisma.PrismaPromise<GetEventUserAggregateType<T>>

  /**
   * Group by EventUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventUserGroupByArgs['orderBy'] }
      : { orderBy?: EventUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventUser model
 */
readonly fields: EventUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventUser model
 */
export interface EventUserFieldRefs {
  readonly id: Prisma.FieldRef<"EventUser", 'Int'>
  readonly userId: Prisma.FieldRef<"EventUser", 'Int'>
  readonly eventId: Prisma.FieldRef<"EventUser", 'Int'>
}
    

// Custom InputTypes
/**
 * EventUser findUnique
 */
export type EventUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * Filter, which EventUser to fetch.
   */
  where: Prisma.EventUserWhereUniqueInput
}

/**
 * EventUser findUniqueOrThrow
 */
export type EventUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * Filter, which EventUser to fetch.
   */
  where: Prisma.EventUserWhereUniqueInput
}

/**
 * EventUser findFirst
 */
export type EventUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * Filter, which EventUser to fetch.
   */
  where?: Prisma.EventUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventUsers to fetch.
   */
  orderBy?: Prisma.EventUserOrderByWithRelationInput | Prisma.EventUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventUsers.
   */
  cursor?: Prisma.EventUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventUsers.
   */
  distinct?: Prisma.EventUserScalarFieldEnum | Prisma.EventUserScalarFieldEnum[]
}

/**
 * EventUser findFirstOrThrow
 */
export type EventUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * Filter, which EventUser to fetch.
   */
  where?: Prisma.EventUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventUsers to fetch.
   */
  orderBy?: Prisma.EventUserOrderByWithRelationInput | Prisma.EventUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventUsers.
   */
  cursor?: Prisma.EventUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventUsers.
   */
  distinct?: Prisma.EventUserScalarFieldEnum | Prisma.EventUserScalarFieldEnum[]
}

/**
 * EventUser findMany
 */
export type EventUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * Filter, which EventUsers to fetch.
   */
  where?: Prisma.EventUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventUsers to fetch.
   */
  orderBy?: Prisma.EventUserOrderByWithRelationInput | Prisma.EventUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventUsers.
   */
  cursor?: Prisma.EventUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventUsers.
   */
  skip?: number
  distinct?: Prisma.EventUserScalarFieldEnum | Prisma.EventUserScalarFieldEnum[]
}

/**
 * EventUser create
 */
export type EventUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * The data needed to create a EventUser.
   */
  data: Prisma.XOR<Prisma.EventUserCreateInput, Prisma.EventUserUncheckedCreateInput>
}

/**
 * EventUser createMany
 */
export type EventUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventUsers.
   */
  data: Prisma.EventUserCreateManyInput | Prisma.EventUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EventUser createManyAndReturn
 */
export type EventUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * The data used to create many EventUsers.
   */
  data: Prisma.EventUserCreateManyInput | Prisma.EventUserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventUser update
 */
export type EventUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * The data needed to update a EventUser.
   */
  data: Prisma.XOR<Prisma.EventUserUpdateInput, Prisma.EventUserUncheckedUpdateInput>
  /**
   * Choose, which EventUser to update.
   */
  where: Prisma.EventUserWhereUniqueInput
}

/**
 * EventUser updateMany
 */
export type EventUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventUsers.
   */
  data: Prisma.XOR<Prisma.EventUserUpdateManyMutationInput, Prisma.EventUserUncheckedUpdateManyInput>
  /**
   * Filter which EventUsers to update
   */
  where?: Prisma.EventUserWhereInput
  /**
   * Limit how many EventUsers to update.
   */
  limit?: number
}

/**
 * EventUser updateManyAndReturn
 */
export type EventUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * The data used to update EventUsers.
   */
  data: Prisma.XOR<Prisma.EventUserUpdateManyMutationInput, Prisma.EventUserUncheckedUpdateManyInput>
  /**
   * Filter which EventUsers to update
   */
  where?: Prisma.EventUserWhereInput
  /**
   * Limit how many EventUsers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventUser upsert
 */
export type EventUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * The filter to search for the EventUser to update in case it exists.
   */
  where: Prisma.EventUserWhereUniqueInput
  /**
   * In case the EventUser found by the `where` argument doesn't exist, create a new EventUser with this data.
   */
  create: Prisma.XOR<Prisma.EventUserCreateInput, Prisma.EventUserUncheckedCreateInput>
  /**
   * In case the EventUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventUserUpdateInput, Prisma.EventUserUncheckedUpdateInput>
}

/**
 * EventUser delete
 */
export type EventUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
  /**
   * Filter which EventUser to delete.
   */
  where: Prisma.EventUserWhereUniqueInput
}

/**
 * EventUser deleteMany
 */
export type EventUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventUsers to delete
   */
  where?: Prisma.EventUserWhereInput
  /**
   * Limit how many EventUsers to delete.
   */
  limit?: number
}

/**
 * EventUser without action
 */
export type EventUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventUser
   */
  select?: Prisma.EventUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventUser
   */
  omit?: Prisma.EventUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventUserInclude<ExtArgs> | null
}
